/** Gallery — real Doris Hair Salon client photos */
window.DORIS_GALLERY = [
  {
    id: "g1",
    src: "images/01-knotless-black-back.jpg",
    alt: "Long black knotless braids from the back with neat square parts in the salon",
    caption: "Knotless braids · client work",
    category: "knotless",
    tall: true,
  },
  {
    id: "g2",
    src: "images/02-ombre-half-up.jpg",
    alt: "Ombre braids from black to copper to blonde in a half-up bun with wavy ends",
    caption: "Ombre goddess braids · client work",
    category: "goddess",
    tall: false,
  },
  {
    id: "g3",
    src: "images/03-black-braids-outdoor.jpg",
    alt: "Long black braids with curly ends worn outdoors at golden hour",
    caption: "Black braids · client work",
    category: "box",
    tall: true,
  },
  {
    id: "g4",
    src: "images/04-black-braids-studio-portrait.jpg",
    alt: "Front portrait of long black box braids with a clean center part",
    caption: "Box braids · client work",
    category: "box",
    tall: false,
  },
  {
    id: "g5",
    src: "images/05-copper-box-twists.jpg",
    alt: "Close-up of copper ombre passion twists with clean box parts",
    caption: "Passion twists · client work",
    category: "twists",
    tall: true,
  },
  {
    id: "g6",
    src: "images/06-ombre-spiral-ends.jpg",
    alt: "Ombre braids with decorative spiral cinnamon-roll ends from the back",
    caption: "Spiral-end braids · client work",
    category: "goddess",
    tall: false,
  },
];
