/** Gallery item data — Unsplash stand-ins until client photos arrive */
window.DORIS_GALLERY = [
  {
    id: "g1",
    src: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?auto=format&fit=crop&w=900&q=80",
    alt: "Placeholder: long knotless braids with soft face-framing pieces",
    caption: "Knotless braids · placeholder photo",
    category: "knotless",
    tall: true,
  },
  {
    id: "g2",
    src: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=900&q=80",
    alt: "Placeholder: styled hair with defined curls and volume",
    caption: "Finish detail · placeholder photo",
    category: "goddess",
    tall: false,
  },
  {
    id: "g3",
    src: "https://images.unsplash.com/photo-1492106087820-71f1a00d2b11?auto=format&fit=crop&w=900&q=80",
    alt: "Placeholder: neat cornrow pattern along the scalp",
    caption: "Cornrows · placeholder photo",
    category: "cornrows",
    tall: false,
  },
  {
    id: "g4",
    src: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&w=900&q=80",
    alt: "Placeholder: protective braided style with warm lighting",
    caption: "Box braids · placeholder photo",
    category: "box",
    tall: true,
  },
  {
    id: "g5",
    src: "https://images.unsplash.com/photo-1580618672591-eb180b1a973f?auto=format&fit=crop&w=900&q=80",
    alt: "Placeholder: soft twist texture close-up",
    caption: "Twists · placeholder photo",
    category: "twists",
    tall: false,
  },
  {
    id: "g6",
    src: "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=900&q=80",
    alt: "Placeholder: salon styling moment with hands in hair",
    caption: "In-salon craft · placeholder photo",
    category: "goddess",
    tall: false,
  },
  {
    id: "g7",
    src: "https://images.unsplash.com/photo-1595476108010-b4d1bc300d3b?auto=format&fit=crop&w=900&q=80",
    alt: "Placeholder: sleek braided updo detail",
    caption: "Cornrow finish · placeholder photo",
    category: "cornrows",
    tall: false,
  },
  {
    id: "g8",
    src: "https://images.unsplash.com/photo-1634445781200-32d50c4e8f6a?auto=format&fit=crop&w=900&q=80",
    alt: "Placeholder: long box braids draped over the shoulder",
    caption: "Box braids · placeholder photo",
    category: "box",
    tall: true,
  },
  {
    id: "g9",
    src: "https://images.unsplash.com/photo-1620331311520-246422fd82f9?auto=format&fit=crop&w=900&q=80",
    alt: "Placeholder: braided style with soft ambient light",
    caption: "Knotless look · placeholder photo",
    category: "knotless",
    tall: false,
  },
];
