/** Gallery — real Hair by Doris client photos */
window.DORIS_GALLERY = [
  {
    id: "g1",
    src: "images/01-knotless-black-back.jpg",
    alt: "Long black knotless braids from the back with neat square parts in the salon",
    caption: "Knotless braids · client work",
    category: "knotless",
    tall: true,
  },
  {
    id: "g2",
    src: "images/02-ombre-half-up.jpg",
    alt: "Ombre braids from black to copper to blonde in a half-up bun with wavy ends",
    caption: "Ombre goddess braids · client work",
    category: "goddess",
    tall: false,
  },
  {
    id: "g3",
    src: "images/03-black-braids-outdoor.jpg",
    alt: "Long black braids with curly ends worn outdoors at golden hour",
    caption: "Goddess braids · client work",
    category: "goddess",
    tall: true,
  },
  {
    id: "g4",
    src: "images/04-black-braids-studio-portrait.jpg",
    alt: "Front portrait of long black loose braids with a clean center part",
    caption: "Loose braids · client work",
    category: "loose",
    tall: false,
  },
  {
    id: "g5",
    src: "images/05-copper-box-twists.jpg",
    alt: "Close-up of copper ombre passion twists with clean box parts",
    caption: "Passion twists · client work",
    category: "twists",
    tall: true,
  },
  {
    id: "g6",
    src: "images/06-ombre-spiral-ends.jpg",
    alt: "Ombre braids with decorative spiral cinnamon-roll ends from the back",
    caption: "Spiral-end braids · client work",
    category: "goddess",
    tall: false,
  },
  {
    id: "g7",
    src: "images/01-mini-twists-semi-human.jpg",
    alt: "Voluminous black mini twists with curly texture, semi-human hair, salon setting",
    caption: "Mini twists (semi-human) · client work",
    category: "twists",
    tall: true,
  },
  {
    id: "g8",
    src: "images/02-unlabeled-teal-outdoor-braids.jpg",
    alt: "Back view of medium boho box braids with neat square parts and curly ends outdoors",
    caption: "Boho box braids · client work",
    category: "box",
    tall: false,
  },
  {
    id: "g9",
    src: "images/03-loose-braids-white-tee.jpg",
    alt: "Back view of long loose braids with burgundy blend and clean parts, white tee",
    caption: "Loose braids · client work",
    category: "loose",
    tall: true,
  },
  {
    id: "g10",
    src: "images/04-unlabeled-auburn-boho-overhead.jpg",
    alt: "Overhead view of auburn goddess boho braids with curly ends and clean box parts",
    caption: "Goddess / boho braids · client work",
    category: "goddess",
    tall: false,
  },
  {
    id: "g11",
    src: "images/05-deep-twists.jpg",
    alt: "Client smiling with deep twists that open into long defined spiral curls",
    caption: "Deep twists · client work",
    category: "twists",
    tall: true,
  },
];
